#
# Gitlab pipeline config
#

stages:
  - compile
  - test
  - build
  - depend-scan
  - deploy


cache:
  paths:
    - .m2/repository
    - target

variables:
  MAVEN_OPT: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"


include: '/templates/Dependency-Scanning.gitlab-ci.yml'


compile:
  image: maven:3.8-openjdk-11
  stage: compile
  script:
    - mvn compile

build:
  image: maven:3.8-openjdk-11
  stage: build
  script:
    - mvn package -s ci_settings.xml

test:
  image: maven:3.8-openjdk-11
  stage: test
  script:
    - mvn test


depend-scan:
  image: maven:3.8-openjdk-11
  stage: depend-scan
  script:
    - mvn test

deploy_to_gitlab_package_registry:
  image: maven:3.8-openjdk-11
  stage: deploy
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - main